"""
Local knowledge module for retrieving information from vector databases.
"""

from typing import List
from langchain_community.vectorstores import FAISS
from langchain.vectorstores.base import VectorStore
from langchain_community.document_loaders import PyPDFLoader, CSVLoader, TextLoader
from langchain.document_loaders.base import BaseLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain.prompts import PromptTemplate
from langchain_openai import OpenAI
from langchain.chains import RetrievalQA


from ..config import EMBEDDINGS_MODEL, CHUNK_SIZE, CHUNK_OVERLAP, NUM_RESULTS


class LocalKnowledge:
    """
    Handles operations related to local knowledge stored in vector databases.
    """

    @staticmethod
    def get_content_with_retrievalqa(vector_db: VectorStore, query: str) -> str:
        """
        Get relevant content from the vector database for a query using RetrievalQA.

        Args:
            vector_db: The vector store to search.
            query: The query string.

        Returns:
            str: The answer generated by the RetrievalQA pipeline.
        """
        try:
            # Configure the retriever
            retriever = vector_db.as_retriever(search_kwargs={"k": NUM_RESULTS})

            # Define a custom prompt for RetrievalQA
            prompt_template = """
            You are a helpful assistant. Use the following documents to answer the user's question.
            If the answer is not in the documents, say "I don't know."

            {context}

            Question: {question}
            Answer:
            """
            prompt = PromptTemplate(
                input_variables=["context", "question"],
                template=prompt_template,
            )

            # Initialize the LLM (e.g., OpenAI or another model)
            llm = OpenAI(
                temperature=0, max_tokens=500,
            )  # Remplacez par votre LLM si nécessaire

            # Create the RetrievalQA pipeline
            qa_chain = RetrievalQA.from_chain_type(
                llm=llm,
                retriever=retriever,
                chain_type="stuff",  # Combine documents into a single context
                chain_type_kwargs={"prompt": prompt},
            )

            # Run the query through the QA pipeline
            answer = qa_chain.run(query)
            return answer.strip()
        except Exception as e:
            print(f"Error in RetrievalQA pipeline: {e}")
            return "I couldn't retrieve an answer. Please try again."

    @staticmethod
    def get_document_loader(file_path: str) -> BaseLoader:
        """
        Get the appropriate document loader based on file extension.

        Args:
            file_path: Path to the document file.

        Returns:
            BaseLoader: The appropriate document loader instance.

        Raises:
            ValueError: If the file format is not supported.
        """
        if file_path.endswith(".pdf"):
            return PyPDFLoader(file_path)
        elif file_path.endswith(".csv"):
            return CSVLoader(file_path)
        elif file_path.endswith(".txt"):
            return TextLoader(file_path)
        else:
            raise ValueError(f"Unsupported file format: {file_path}")

    @staticmethod
    def setup_vector_db(file_paths: List[str]) -> VectorStore:
        """
        Set up a vector database from document files.

        Args:
            file_paths: List of paths to document files.

        Returns:
            VectorStore: The created vector store.
        """
        all_documents = []

        # Load all documents
        for file_path in file_paths:
            try:
                loader = LocalKnowledge.get_document_loader(file_path)
                documents = loader.load()
                all_documents.extend(documents)
            except Exception as e:
                print(f"Error loading {file_path}: {e}")

        # Split documents into chunks
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP
        )
        chunks = text_splitter.split_documents(all_documents)

        # Create vector database
        try:
            embeddings = OpenAIEmbeddings(model=EMBEDDINGS_MODEL)
            vector_db = FAISS.from_documents(chunks, embeddings)
            return vector_db
        except Exception as e:
            print(f"Error creating vector database: {e}")
            return None

    @staticmethod
    def get_content(vector_db: VectorStore, query: str) -> str:
        """
        Get relevant content from the vector database for a query.

        Args:
            vector_db: The vector store to search.
            query: The query string.

        Returns:
            str: The concatenated content of the most relevant documents.
        """
        docs = vector_db.similarity_search(query, k=NUM_RESULTS)
        return " ".join([doc.page_content for doc in docs])
